services:
    # ...
    admin.book:
        class: AppBundle\Admin\BookAdmin
        arguments: [~, AppBundle\Entity\Book, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
